import type { Metadata } from "next";
import { Aladin, Lexend, Noto_Sans_Bengali } from "next/font/google";
import "@/styles/globals.css";
import ConditionalProviders from "@/providers/ConditionalProviders/index";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  display: "swap",
});

const notoSansBengali = Noto_Sans_Bengali({
  variable: "--font-noto-sans-bengali",
  subsets: ["latin", "bengali"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ConditionalProviders className={` ${lexend.className}  antialiased`}>
        {children}
      </ConditionalProviders>
    </html>
  );
}
